import Providers from "@/components/DndProvider/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section
      className="grow bg-gradient-to-br from-indigo from-20% to-light-purple 
      to-100% w-[calc(100wh-144px)] overflow-x-scroll"
    >
      <Providers>{children}</Providers>
    </section>
  );
}
